### ISSUE TITLE
Coordinator View - Backend create view for course evaluation

### ISSUE THREAD

**Issue by peter-tanner** [uwasystemhealth/IndEAAv2#10]
## What needs to be done?
When creating a course evaluation (See #9), create a new entry in the `courseEvaluation` table. Populate the unit code, description and coordinators (I think by default we have the creator as the first coordinator in the list. Admin can add more users as coordinators later, outside of this issue.)

## Other
Refers to 16 from our discussion
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64839317/175465432-a13eedc0-42a5-427a-bbbc-18e02be9e72e.png)

**Comment by MouseAndKeyboard** [comment]
Just clarifying, my understanding was that the flow would be like this:
1. Because Michael has the "coordinator" permission/role in the database, he can create a new evaluation for GENG1234.
2. Because Michael is the user who created the GENG1234 evaluation he is able to invite other users with the "coordinator" permission. let's say he invites his fellow coordinator: Frinze.
3. Frinze now has the same level of authority as Michael over the GENG1234 course evaluation (and could in theory remove Michael).

Admins don't really need to be involved with any of this.

**Comment by frinzekt** [comment]
admins has the ability via Django admin (for everything), but if they want to see things in the panel, they need to be added as a coordinator

**Comment by frinzekt** [comment]
This is very much related to #34 in an implied way. So when accomplishing this task, I will bundle it to the same change

**Comment by frinzekt** [comment]
For ease of tracking, I will just implement this within #34
