### ISSUE TITLE
Coordinator View - Course Evaluation (API) 

### ISSUE THREAD

**Issue by chayG5** [uwasystemhealth/IndEAAv2#20]
## What needs to be done?
- Detail view 
- Update view (the coordinator can update attributes of the evaluation i.e. title, start date, unit being reviewed, description or content of materials)

![image](https://user-images.githubusercontent.com/104259880/175235288-58c6af26-646a-4219-9fa0-e2912d17bf9a.png)

## Other
Refers to 11 from our discussion
![MicrosoftTeams-image](https://user-images.githubusercontent.com/64839317/175464146-3de80a43-0187-426d-b5f7-89c78346fbfc.png)

**Comment by frinzekt** [comment]
> Detail view
Has already been implemented as part of #39 (due to OOP of Django) "Create View".
The test associated to this is `test_create_view_course_evaluation`. This test just shows a much more details version of it.

This is also the foundation set by @chayG5  in #46 for #21

> Update view (the coordinator can update attributes of the evaluation i.e. title, start date, unit being reviewed, description or content of materials)

This particular view has already been created as well as part of #39 "Update View".
The test associated to this is `test_update_view_course_evaluation`. This shows a simple way of just modifying the description.

**Comment by frinzekt** [comment]
Closing as complete then as the API change already exist
