### ISSUE TITLE
User Administration 

### ISSUE THREAD

**Issue by ivy0305** [uwasystemhealth/IndEAAv2#28]
## What needs to be done?
- Verify add user
- Edit permission

**Comment by MouseAndKeyboard** [comment]
How are we going to do this? Same as Indeaa v1?

**Comment by MouseAndKeyboard** [comment]
Verify add user could refer to 2 things:
1. Just add a small popup or something when you add a new user making sure you really intend to add them.
2. Adding email verification system, so when a user is invited to the system (either as a coordinator or reviewer) they receive an email alerting them that they have been invited.

Edit permission:
There are 2 main tiers of permissions:

1. Coordinators (who have the ability to create new Course Evaluations)
3. Administrators (who are able to promote other users to coordinators)

My question:

How do we deal with the following situation?
A coordinator creates a course evaluation and then invites another user to help co-coordinate the course evaluation.
BUT: Should this co-coordinator now have the permission to CREATE their own evaluations?

**Comment by frinzekt** [comment]
I have again ran into the same issue @MouseAndKeyboard ... in the initial design of IndEAAv1, we always have done it that way.

Currently due to the #22, there needs to be an endpoint listing all the EOC to select to create one. I am thinking if it is even needed as part of MVP.

I am thinking of closing this issue because we can add user through the django admin and edit who the coordinators are, and even reviewers...

From a usage perspective, it is not often that the coordinator creates the course evaluation anyways (if they do, they do it once... and thats that)...

**Comment by frinzekt** [comment]
happy to revisit this at a later stage, but for now im closing this
