### ISSUE TITLE
Google Oauth

### ISSUE THREAD

**Issue by ivy0305** [uwasystemhealth/IndEAAv2#29]
## What needs to be done?
Allows users to be able to login using their Google account, instead of logging in using an email/username and password.

**NOTE:** This issue requires issue #28 to be completed first, and has both a frontend and backend component. These components are: 
- [ ] Backend Oauth setup
- [ ] Frontend communicating to backend for Oauth

**Comment by peter-tanner** [comment]
test

**Comment by peter-tanner** [comment]
- [ ] bugs - sometimes google says the redirect url is wrong (fix with refresh, nto sure if this is a configuration error)
- [ ] bug: not sure what I changed but now I'm getting this error: Error: Text content does not match server-rendered HTML.
 - [ ] currently need to change:
```py
def _complete_social_login(request, sociallogin):
  if request.user.is_authenticated:
```
to
```py
def _complete_social_login(request, sociallogin):
  if request.user and request.user.is_authenticated:
```
in `\usr\local\lib\python3.9\site-packages\allauth\socialaccount\helpers.py`. Check if the bug exists on newer Allauth versions

- [ ] Make better login page
- [ ] Logout does not currently work
- [ ] Seriously clean up code

see branch 29-google-oauth

**Comment by peter-tanner** [comment]
Having issues getting it integrated with react frontend, I need to pass a CSRF token for it to work. But it seems I can only pass it as a cookie for it to work (and broswer does not allow this to occur). Putting the token in the header as suggested online doesn't seem to work either.

this doesn't work
`curl "http://localhost:8000/api/v1/authentication/google/login/" -H "X-CSRFTOKEN: xHg8DtQ8EWCwjrYJHw0Z2gvalAiSTDVRZfKrcjxswCGcHPyl5Rbhk57AETVYPR9A"  --data-raw "csrfmiddlewaretoken=eBz8HN11hUykVJo9vPcjwfOAQhFRTVteG93rgDIl9AC0j7YLTanBO4q09AiXP9HX" -L`

this works but cannot occur because browser doesn't allow me to set the cookie directly
`curl "http://localhost:8000/api/v1/authentication/google/login/" -H "Cookie: tabstyle=html-tab; csrftoken=xHg8DtQ8EWCwjrYJHw0Z2gvalAiSTDVRZfKrcjxswCGcHPyl5Rbhk57AETVYPR9A"  --data-raw "csrfmiddlewaretoken=eBz8HN11hUykVJo9vPcjwfOAQhFRTVteG93rgDIl9AC0j7YLTanBO4q09AiXP9HX" -L`

I can also just link directly to the authentication page, although this is annoying as the google client_id is set as an environment variable and this doesn't have that. I can serve these items from an api endpoint and construct the url in the client.
