### ISSUE TITLE
Basic Login Authentication

### ISSUE THREAD

**Issue by ivy0305** [uwasystemhealth/IndEAAv2#30]
## What needs to be done?
Being able to login as with email and password using the default Django JWT

## User Story
As a user, I can login using my email and password.

## Other information
This will be extended later on by #29

**Comment by MouseAndKeyboard** [comment]
So are we going to also have a typical username:password login flow NOT using Google login?
This requires handling:
- [ ] Password resetting (via email)
- [ ] Managing passwords in our database (thus security implications)

**Comment by frinzekt** [comment]
Django automatically handles the encryption of password for us. We don't need password reset system because we can do that straight from Django as an admin.

**Comment by frinzekt** [comment]
We are going to use Google Oauth. The main reason we have this is it makes it easier to do integration testing with Cypress. And the fact that Django already ships the entire user authentication for us without doing any extra work

**Comment by frinzekt** [comment]
Note, I have to create the API endpoints for authentication

**Comment by Tommo303** [comment]
#29 LInk to google authentication

**Comment by Tommo303** [comment]
Frontend and backend work but needs designing.

**Comment by frinzekt** [comment]
A tiny request, @peter-tanner , can you move the "Login With Google" to the top,  add a horizontal divider (https://mui.com/material-ui/react-divider/#dividers-with-text). The text could be something like "OR login with Email/Password"

From a UI design (because we humans usually start from the top to bottom when reading/looking), this suggest to the user to try the first action first.
