### ISSUE TITLE
Deployment of documentation 

### ISSUE THREAD

**Issue by ivy0305** [uwasystemhealth/IndEAAv2#31]
## What needs to be done?
Deploy documentation on SHL's VPS

**Comment by MouseAndKeyboard** [comment]
I guess this and issue #32 acheive the same thing? Since the whole project is using docker-compose, deploying in one place will deploy the documentation, frontend, backend, etc all at the same time

**Comment by frinzekt** [comment]
@MouseAndKeyboard... I will prefer to deploy the documentation in github pages (similar to how we have it in indeaav1) because we can (we are allowed to host a frontend as part of having a repo). 

This is also good because we reduce the computing requirements in the VPS when we can.

> Why not the frontend in github pages?
Deploying mkdocs is easier. Nextjs, technically we can deploy it in github pages, but we need to do some extra research on that whereas mkdocs is just present

**Comment by frinzekt** [comment]
looks like we already have it in certain extent see https://uwasystemhealth.github.io/IndEAAv2/

just need the domain name, i think
