### ISSUE TITLE
Coordinator View - Frontend for 'Course Evaluation' List

### ISSUE THREAD

**Issue by ivy0305** [uwasystemhealth/IndEAAv2#33]
## What needs to be done?
- The first page you see in the coordinator view 
- Includes:
    - For each course evaluation:
      - Unit code
      - Coordinators 
      - Unit description
      - A button that takes you to the page showing more information for the course evaluation 
     - A button to create a new course evaluation
     - A button to see archived course evaluations 
- This page refers to:
<img width="1492" alt="Screen Shot 2022-06-23 at 6 45 49 pm" src="https://user-images.githubusercontent.com/64839317/175282285-dbfae78e-8861-42b1-944d-13a7043ca654.png">

## Other
Refers to 9 from our discussion
![MicrosoftTeams-image](https://user-images.githubusercontent.com/64839317/175478355-851d486c-5c67-482d-b3c9-9a416c81ff39.png)

**Comment by frinzekt** [comment]
Before this can begin #39 #38  needs to be merged first because auth is required for viewing the listing.

I am removing myself as an assignee for this one because I believe someone else should pick this up. The main reason being is that
I have written code in #38 that uses `useSWRAuth` to get information from a specific endpoint. And the code written in #39  shows the endpoint that you will use in this issue. Put those two knowledge together,  this one will be easy peacy.

In terms of the `Create New Evaluation`. You will need to use the `useAuthenticatedAPIClient` as per #38 (specifically `axios.post` to the endpoint that is created in #39) to deliver the payload body. 

PS @uwasystemhealth/redbacks

**Comment by chayG5** [comment]
@Tommo303 Hi, Frinze and I were going through how the landing page was going to work and what was going to happen after logging in. We went through how to display the different course evaluations for the coordinator, which is up and working now. We  are going to have the coordinator listing and review listing show on the same page after logging in.

**Comment by frinzekt** [comment]
Link #41
