### ISSUE TITLE
Hydration error[BUG]

### ISSUE THREAD

**Issue by chayG5** [uwasystemhealth/IndEAAv2#43]
## Describe the bug
Hydration error: 

![image](https://user-images.githubusercontent.com/104259880/178889190-6e4dfc92-4251-4f76-b8d6-54d8486dce60.png)
![image](https://user-images.githubusercontent.com/104259880/178889231-64ff182d-2f38-47f4-926e-c4963dc9e1bd.png)
![image](https://user-images.githubusercontent.com/104259880/178889265-0556fad9-f24e-436c-9c23-f3ada1cd293a.png)

### To Reproduce
1. docker-compose up on landing page branch

**Comment by frinzekt** [comment]
to make debugging easier... The reason why this is happening is because the "server-side render" of nextJS is resulting with a different data or display upon when it is loaded by "client-side render".

The libraries that are good to look into in terms of integration are:
- swr
- nextjs
- material ui

**Comment by frinzekt** [comment]
Closer dive on the issue reveals it is SWR see https://github.com/vercel/swr/issues/1906 ... this explains why I have never faced this issue before... For the fact that we don't need react to be version 18 specifically, I will be reverting it to around `^17.0.2` (same as spontane)
