### ISSUE TITLE
Feedback from IAP

### ISSUE THREAD

**Issue by chayG5** [uwasystemhealth/IndEAAv2#48]
## What needs to be done/changed?
- [ ] Course evaluation page – when view button clicked, provide the unit code somewhere as well
- [ ] “Is there any intention for contact details (email) to be provided if a question regarding the course arises during the review process?”
- [ ] “Is the user able to download the documents (pdf download can make for an easier read/ markup process)?”
- [ ] Some confusion about adding comment to a document:

    o	 “What features are included in the comment button, is this a general text box entry for the whole document?”
    o	 “Are comments mandatory or optional?” –> it is unclear which fields are mandatory and which fields are not.
    o	 “Are there any requirements/conventions for making comments?”
- [ ] “EOC abbreviation explanation on first usage”
- [ ] “Identify if there are any software requirements associated with the review process e.g. is everything embedded and you just need a web browser (min ? version) or is Adobe PDF viewer or Adobe Pro required”

**Comment by chayG5** [comment]
@frinzekt these are some feedback sent by the IAP

**Comment by frinzekt** [comment]
> Course evaluation page – when view button clicked, provide the unit code somewhere as well
Yeah, i think we will need to display the currently being viewed unit at the top of the page (header or the top of the body card)

> “Is there any intention for contact details (email) to be provided if a question regarding the course arises during the review process?”

Yeah we can do this... because all users have email address ,

>  “Is the user able to download the documents (pdf download can make for an easier read/ markup process)?”
User
- for documents, they can download the document if they want to as it will essentially just take them to a link of the google drive
- for report summary, this can be downloaded later on by the coordinator... this is related to #19 

> “EOC abbreviation explanation on first usage”
can do

> “Identify if there are any software requirements associated with the review process e.g. is everything embedded and you just need a web browser (min ? version) or is Adobe PDF viewer or Adobe Pro required”

Yeah just need a web browser. The minimum version of browser will are below

Browser | Version | Date
-- | -- | --
Chrome | 51 | May 2016
Firefox | 52 | Mar 2017
Edge | 14 | Aug 2016
Safari | 10 | Sep 2016
Opera | 38 | Jun 2016

With reference to: https://www.w3schools.com/js/js_versions.asp (ES6 - ES2015).

In terms of PDF viewer, the browser that is being used usually has the necessary viewer. This is assuming that the pdf is being viewed through google drive for example. If it is downloaded, then it becomes the responsibility of who is using the computer to have the necessary tools for viewing.

However, do note that to get the best experience. Have a browser that is updated atleast 2017 (yeah we support things from 5 years ago).

**Comment by frinzekt** [comment]
I will be closing this now... I have mentioned the relevant github issue such that the feedbacks are embedded now to those github issues
